name: Build
on: 
    workflow_dispatch:
    repository_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Builds Typescript
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Update Dependencies
        run: |
          rm ./js/*.*
          wget https://raw.githubusercontent.com/DaLLuZZ/Facepunch.WebGame/master/js/facepunch.webgame.d.ts -P ./js/
          wget https://raw.githubusercontent.com/DaLLuZZ/SourceUtils/master/SourceUtils.WebExport/Resources/js/sourceutils.d.ts -P ./js/

      - name: Building Typescript
        uses: FuLagann/tsc-build-push@v1
        with:
          user-name: "DaLLuZZ"
          user-email: "khrushiov2012@yandex.ru"
          message: "Automatic build"
          directories: ./

      - name: Update JS on GitHub Pages
        run: |
          git fetch
          git checkout gh-pages
          wget https://raw.githubusercontent.com/DaLLuZZ/Facepunch.WebGame/master/js/facepunch.webgame.js -P ./js/
          wget https://raw.githubusercontent.com/DaLLuZZ/SourceUtils/master/SourceUtils.WebExport/Resources/js/sourceutils.js -P ./js/
          wget https://raw.githubusercontent.com/DaLLuZZ/SourceUtils/master/SourceUtils.WebExport/Resources/js/sourceutils.js -P ./js/
          git config user.name DaLLuZZ
          git config user.email khrushiov2012@yandex.ru
          git add .
          git commit -m "Automatic JS update"
          git push
